### ISSUE TITLE
changing url at runtime

### ISSUE THREAD

**Issue by joleeee** [maplibre/maplibre-gl-directions#242]
is this supported? update the api url and recalculate path

**Comment by smellyshovel** [comment]
@joleeee As far as I remember, no. You'd have to re-instantiate the Directions object with a new URL instead.
On the other hand, it is possible to save the currently displayed routes before doing so and then re-apply them after re-instantiating the instance, thus creating an illusion of a seamless URL change.

Otherwise, it should also be pretty straightforward to implement on the library level. So feel free to open a PR, if you decide to work on this.

**Comment by joleeee** [comment]
Given that it only happens with this package, I'm thinking it might be a package.json type of bug. Maybe the dependency is not pruned when building for dev, or when building for production in the standard way.

I will try making a small MVP by the weekend

**Comment by smellyshovel** [comment]
> Given that it only happens with this package, I'm thinking it might be a package.json type of bug. Maybe the dependency is not pruned when building for dev, or when building for production in the standard way.
> 
> I will try making a small MVP by the weekend

I'd argue that the `package.json` is a pretty standard one. But yeah, would be nice if you could create a repro. LMK when there's any update.
